Repository matheus-de-araujo/calculadora, pull requests merged in 2022-05, with the labels that each got.

#11 CAL-3
  .gitignore
  src/main/java/com/calculadora/Calculadora.java
Labels: feature

#15 CAL-13
  src/main/java/com/calculadora/App.java
  src/main/java/com/calculadora/Calculadora.java
  src/main/java/com/calculadora/CalculadoraBasica.java
Labels: feature

#17 CAL-16
  src/main/java/com/calculadora/CalculadoraBasica.java
Labels: Aguardando Revisão

#18 CAL-12
  src/main/java/com/calculadora/CalculadoraBasica.java
Labels: Aguardando Revisão

#20 CAL-19
  src/main/java/com/calculadora/CalculadoraBasica.java
Labels: Aguardando Revisão

#14 CAL-9
  src/main/java/com/calculadora/App.java
  src/main/java/com/calculadora/InterfaceInteracao.java
Labels: Em desenvolvimento

#29 Cal 28
  src/main/java/com/calculadora/CalculadoraCientifica.java
Labels: Aguardando Revisão

#31 Cal 30
  src/main/java/com/calculadora/CalculadoraCientifica.java
Labels: Aguardando Revisão

#34 CAL-22
  src/main/java/com/calculadora/CalculadoraCientifica.java
Labels: Aguardando Revisão
